POST   http://localhost:3000/user/SignUp

{
  "name": "AdminUser",
  "email": "admin123@email.com",
  "role": "admin", // Role set to 'admin'
  "password": "SecurePassword123@",
  "profile_img": ["1732624107084-images (3).jpg"]
}