POST   http://localhost:3000/api/products/createProduct
Content-Type: application/json

 {
    "name": "Team Jersey - Home",
    "category": "Jerseys",
    "price": 79.99,
    "description": "Official home jersey for the 2023 season, featuring lightweight fabric for comfort and performance.",
     "stockQuantity" : "3",
    "img": "https://example.com/images/home-jersey.jpg"
  }